const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');const root=path.resolve(__dirname,'..'),original=Module._load;let session={user:{id:'synthetic'}},dbCalls=0;
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,f);
Module._load=function(r,p,m){if(r==='@/lib/security/patient')return {getPatientSession:async()=>session};if(r==='@/lib/notifications/email')return {};if(r==='@/lib/supabase/server')return {createServiceClient:()=>{dbCalls++;throw Error('Unexpected database call')}};if(r.startsWith('@/'))r=path.join(root,r.slice(2));return original.call(this,r,p,m);};
const {POST}=require('../app/api/intake/route.ts');
test('explicit submission still rejects missing treatment before any database write',async()=>{
 session={user:{id:'synthetic'}};
 const payload={assistanceType:'hospital',patient:{firstName:'SYNTHETIC',lastName:'TEST',dateOfBirth:'1960-01-01',phone:'6025550100',email:'synthetic@example.test',addressLine1:'123 Test Street',city:'Phoenix',state:'AZ',postalCode:'85001',employmentStatus:'Retired',incomeSources:[]},representative:{hasRepresentative:false},diagnosis:{cancerType:'Synthetic test',diagnosisDate:'2026-01',treatments:[],medications:[]},provider:{clinicName:'HonorHealth',providerName:'Synthetic provider'},hospital:{treatmentFacilities:['HonorHealth Cancer Care']},insurance:{hasInsurance:false,hasMedicalInsurance:false,hasPharmacyInsurance:false,hasMedicare:false,hasMedicaid:false,coverageDenied:'not_sure',eobAvailable:false},household:{monthlyIncome:1000,annualIncome:12000,householdSize:1,employmentStatus:'Retired',members:[]},consent:{volunteerAccessConsent:true,releaseMedicalFinancial:true,contactPermission:true,noGuaranteeAcknowledgment:true,signature:'SYNTHETIC TEST',signedAt:'2026-09-25T12:00:00.000Z'}};
 const body=new FormData();body.append('submissionIntent','patient-confirmed');body.append('payload',JSON.stringify(payload));
 const response=await POST(new Request('https://portal.example/api/intake',{method:'POST',body}));
 assert.equal(response.status,400);assert.match((await response.json()).error,/At least one treatment is required/);assert.equal(dbCalls,0);
});
test('saving or visiting review cannot create a submission without explicit final intent',async()=>{const body=new FormData();body.append('payload',JSON.stringify({consent:{volunteerAccessConsent:true,signature:'SYNTHETIC'}}));const response=await POST(new Request('https://portal.example/api/intake',{method:'POST',body}));assert.equal(response.status,400);assert.match((await response.json()).error,/confirm Submit/);assert.equal(dbCalls,0);session=null;assert.equal((await POST(new Request('https://portal.example/api/intake',{method:'POST',body}))).status,401);assert.equal(dbCalls,0);});
