export const legacyMedications = [
  "Abemaciclib (Verzenio)",
  "Abiraterone (Zytiga)",
  "Acalabrutinib (Calquence)",
  "Adagrasib (Krazati)",
  "Afatinib (Gilotrif)",
  "Alectinib (Alecensa)",
  "Alemtuzumab (Campath)",
  "Alpelisib (Piqray)",
  "Amivantamab (Rybrevant)",
  "Anastrozole (Arimidex)",
  "Apalutamide (Erleada)",
  "Arsenic trioxide (Trisenox)",
  "Asciminib (Scemblix)",
  "Atezolizumab (Tecentriq)",
  "Avapritinib (Ayvakit)",
  "Avelumab (Bavencio)",
  "Axitinib (Inlyta)",
  "Azacitidine (Vidaza, Onureg)",
  "Belantamab mafodotin (Blenrep)",
  "Belzutifan (Welireg)",
  "Bendamustine (Bendeka, Treanda)",
  "Bevacizumab (Avastin)",
  "Bicalutamide (Casodex)",
  "Binimetinib (Mektovi)",
  "Blinatumomab (Blincyto)",
  "Bortezomib (Velcade)",
  "Bosutinib (Bosulif)",
  "Brentuximab vedotin (Adcetris)",
  "Brexucabtagene autoleucel (Tecartus)",
  "Brigatinib (Alunbrig)",
  "Busulfan (Busulfex, Myleran)",
  "Cabazitaxel (Jevtana)",
  "Cabozantinib (Cabometyx, Cometriq)",
  "Calaspargase pegol (Asparlas)",
  "Capecitabine (Xeloda)",
  "Capivasertib (Truqap)",
  "Capmatinib (Tabrecta)",
  "Carboplatin (Paraplatin)",
  "Carfilzomib (Kyprolis)",
  "Carmustine (BiCNU, Gliadel)",
  "Cemiplimab (Libtayo)",
  "Ceritinib (Zykadia)",
  "Cetuximab (Erbitux)",
  "Chlorambucil (Leukeran)",
  "Cisplatin (Platinol)",
  "Cladribine (Leustatin)",
  "Cobimetinib (Cotellic)",
  "Copanlisib (Aliqopa)",
  "Crizotinib (Xalkori)",
  "Cyclophosphamide (Cytoxan)",
  "Cytarabine (Cytosar-U)",
  "Dabrafenib (Tafinlar)",
  "Dacomitinib (Vizimpro)",
  "Daratumumab (Darzalex, Darzalex Faspro)",
  "Darolutamide (Nubeqa)",
  "Dasatinib (Sprycel)",
  "Daunorubicin (Cerubidine)",
  "Decitabine (Dacogen)",
  "Degarelix (Firmagon)",
  "Denosumab (Xgeva, Prolia)",
  "Dinutuximab (Unituxin)",
  "Docetaxel (Taxotere)",
  "Dostarlimab (Jemperli)",
  "Doxorubicin (Adriamycin, Doxil)",
  "Durvalumab (Imfinzi)",
  "Duvelisib (Copiktra)",
  "Elacestrant (Orserdu)",
  "Elotuzumab (Empliciti)",
  "Enasidenib (Idhifa)",
  "Encorafenib (Braftovi)",
  "Enfortumab vedotin (Padcev)",
  "Entrectinib (Rozlytrek)",
  "Enzalutamide (Xtandi)",
  "Epcoritamab (Epkinly)",
  "Erdafitinib (Balversa)",
  "Erlotinib (Tarceva)",
  "Etoposide (Etopophos, Toposar)",
  "Everolimus (Afinitor)",
  "Exemestane (Aromasin)",
  "Fam-trastuzumab deruxtecan (Enhertu)",
  "Fedratinib (Inrebic)",
  "Fludarabine (Fludara)",
  "Fluorouracil / 5-FU (Adrucil)",
  "Flutamide",
  "Fulvestrant (Faslodex)",
  "Futibatinib (Lytgobi)",
  "Gefitinib (Iressa)",
  "Gemcitabine (Gemzar)",
  "Gemtuzumab ozogamicin (Mylotarg)",
  "Gilteritinib (Xospata)",
  "Glasdegib (Daurismo)",
  "Goserelin (Zoladex)",
  "Hydroxyurea (Hydrea)",
  "Ibrutinib (Imbruvica)",
  "Idarubicin (Idamycin)",
  "Idelalisib (Zydelig)",
  "Ifosfamide (Ifex)",
  "Imatinib (Gleevec)",
  "Infigratinib (Truseltiq)",
  "Inotuzumab ozogamicin (Besponsa)",
  "Interferon alfa-2b (Intron A)",
  "Ipilimumab (Yervoy)",
  "Irinotecan (Camptosar)",
  "Isatuximab (Sarclisa)",
  "Ivosidenib (Tibsovo)",
  "Ixazomib (Ninlaro)",
  "Lapatinib (Tykerb)",
  "Larotrectinib (Vitrakvi)",
  "Lanreotide (Somatuline Depot)",
  "Lenalidomide (Revlimid)",
  "Lenvatinib (Lenvima)",
  "Letrozole (Femara)",
  "Leucovorin",
  "Leuprolide (Lupron Depot, Eligard, Camcevi)",
  "Lisocabtagene maraleucel (Breyanzi)",
  "Lorlatinib (Lorbrena)",
  "Lutetium Lu 177 dotatate (Lutathera)",
  "Lutetium Lu 177 vipivotide tetraxetan (Pluvicto)",
  "Mechlorethamine (Valchlor)",
  "Melphalan (Alkeran)",
  "Mercaptopurine (Purinethol, Purixan)",
  "Methotrexate (Trexall, Otrexup, Rasuvo)",
  "Midostaurin (Rydapt)",
  "Mirvetuximab soravtansine (Elahere)",
  "Mitomycin (Mutamycin)",
  "Mitoxantrone (Novantrone)",
  "Nab-paclitaxel (Abraxane)",
  "Naxitamab (Danyelza)",
  "Neratinib (Nerlynx)",
  "Nilotinib (Tasigna)",
  "Nilutamide (Nilandron)",
  "Niraparib (Zejula)",
  "Nivolumab (Opdivo)",
  "Nivolumab and relatlimab (Opdualag)",
  "Obinutuzumab (Gazyva)",
  "Ofatumumab (Arzerra)",
  "Olaparib (Lynparza)",
  "Osimertinib (Tagrisso)",
  "Oxaliplatin (Eloxatin)",
  "Paclitaxel (Taxol)",
  "Palbociclib (Ibrance)",
  "Pamidronate (Aredia)",
  "Panitumumab (Vectibix)",
  "Pazopanib (Votrient)",
  "Pegaspargase (Oncaspar)",
  "Pemetrexed (Alimta)",
  "Pembrolizumab (Keytruda)",
  "Pertuzumab (Perjeta)",
  "Pirtobrutinib (Jaypirca)",
  "Polatuzumab vedotin (Polivy)",
  "Ponatinib (Iclusig)",
  "Pralsetinib (Gavreto)",
  "Procarbazine (Matulane)",
  "Radium Ra 223 dichloride (Xofigo)",
  "Ramucirumab (Cyramza)",
  "Regorafenib (Stivarga)",
  "Relugolix (Orgovyx)",
  "Repotrectinib (Augtyro)",
  "Ribociclib (Kisqali)",
  "Ripretinib (Qinlock)",
  "Rituximab (Rituxan, Truxima, Ruxience, Riabni)",
  "Romidepsin (Istodax)",
  "Rucaparib (Rubraca)",
  "Ruxolitinib (Jakafi)",
  "Sacituzumab govitecan (Trodelvy)",
  "Selinexor (Xpovio)",
  "Selpercatinib (Retevmo)",
  "Selumetinib (Koselugo)",
  "Sonidegib (Odomzo)",
  "Sorafenib (Nexavar)",
  "Sotorasib (Lumakras)",
  "Sunitinib (Sutent)",
  "Talazoparib (Talzenna)",
  "Tamoxifen (Soltamox)",
  "Tazemetostat (Tazverik)",
  "Temozolomide (Temodar)",
  "Temsirolimus (Torisel)",
  "Tepotinib (Tepmetko)",
  "Thioguanine (Tabloid)",
  "Tisagenlecleucel (Kymriah)",
  "Tisotumab vedotin (Tivdak)",
  "Topotecan (Hycamtin)",
  "Toripalimab (Loqtorzi)",
  "Tovorafenib (Ojemda)",
  "Trametinib (Mekinist)",
  "Trastuzumab (Herceptin, Ogivri, Kanjinti, Trazimera)",
  "Trastuzumab emtansine (Kadcyla)",
  "Tretinoin / ATRA (Vesanoid)",
  "Trifluridine and tipiracil (Lonsurf)",
  "Triptorelin (Trelstar)",
  "Tucatinib (Tukysa)",
  "Vandetanib (Caprelsa)",
  "Venetoclax (Venclexta)",
  "Vinblastine (Velban)",
  "Vincristine (Oncovin, Vincasar PFS)",
  "Vinorelbine (Navelbine)",
  "Vismodegib (Erivedge)",
  "Vorasidenib (Voranigo)",
  "Zanubrutinib (Brukinsa)",
  "Ziv-aflibercept (Zaltrap)",
  "Zoledronic acid (Zometa, Reclast)",
  "Zolbetuximab (Vyloy)",
];
