import { TextAreaField, TextField } from "@/components/ui/Field";
import type { IntakePayload, MayoFinancialAssistance } from "@/lib/types";

type Props = {
  value: MayoFinancialAssistance;
  patient: IntakePayload["patient"];
  onChange: (value: Partial<MayoFinancialAssistance>) => void;
};

const employmentOptions = ["Full time", "Part time", "Self employed", "Unemployed", "Student"];

function YesNo({ label, value, onChange }: { label: string; value: "yes" | "no" | ""; onChange: (value: "yes" | "no") => void }) {
  return <fieldset className="grid gap-2"><legend className="text-sm font-medium text-ink">{label}</legend><div className="flex gap-5">{(["yes", "no"] as const).map((option) => <label key={option} className="flex items-center gap-2 text-sm"><input type="radio" checked={value === option} onChange={() => onChange(option)} />{option === "yes" ? "Yes" : "No"}</label>)}</div></fieldset>;
}

export function MayoFinancialAssistanceSection({ value, patient, onChange }: Props) {
  const toggleRelationship = (relationship: string, checked: boolean) => onChange({ relationshipToPatient: checked ? [...new Set([...value.relationshipToPatient, relationship])] : value.relationshipToPatient.filter((item) => item !== relationship) });
  return <section className="grid gap-5 rounded-md border-2 border-pine/20 bg-pine/5 p-5 md:col-span-2">
    <div><h3 className="text-lg font-semibold">Mayo Clinic Arizona financial assistance</h3><p className="mt-1 text-sm leading-6 text-slate-600">These additional questions match the information Mayo Clinic requests. Information already entered above is carried into this section automatically.</p></div>
    <fieldset className="grid gap-2"><legend className="text-sm font-medium">Relationship to the patient (optional; select all that apply)</legend>{["I am the patient", "I am responsible for the patient's medical expenses"].map((item) => <label key={item} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.relationshipToPatient.includes(item)} onChange={(e) => toggleRelationship(item, e.target.checked)} />{item}</label>)}</fieldset>
    <div className="grid gap-4 md:grid-cols-3"><TextField label="Applicant first name" value={value.applicantFirstName || patient.firstName} onChange={(e) => onChange({ applicantFirstName: e.target.value })} /><TextField required label="Applicant middle name or initial" placeholder='Enter "not applicable" if none' value={value.applicantMiddleName} onChange={(e) => onChange({ applicantMiddleName: e.target.value })} /><TextField label="Applicant last name" value={value.applicantLastName || patient.lastName} onChange={(e) => onChange({ applicantLastName: e.target.value })} /></div>
    <div className="grid gap-4 md:grid-cols-2"><TextField label="Mayo Clinic number (optional)" value={value.mayoClinicNumber ?? ""} onChange={(e) => onChange({ mayoClinicNumber: e.target.value })} /><TextField label="Responsible party birth date" type="date" value={value.responsiblePartyBirthDate || patient.dateOfBirth} onChange={(e) => onChange({ responsiblePartyBirthDate: e.target.value })} /><TextField label="Marital status (optional)" value={value.maritalStatus ?? ""} onChange={(e) => onChange({ maritalStatus: e.target.value })} /><TextField label="If unemployed, date or length of unemployment" value={value.unemployedSince ?? ""} onChange={(e) => onChange({ unemployedSince: e.target.value })} /></div>
    <YesNo label="Are you claimed on another tax return?" value={value.claimedOnAnotherTaxReturn} onChange={(claimedOnAnotherTaxReturn) => onChange({ claimedOnAnotherTaxReturn })} />
    <TextAreaField required label="Describe your need for financial assistance" value={value.assistanceNeed} onChange={(e) => onChange({ assistanceNeed: e.target.value })} />
    <div className="grid gap-3"><YesNo label="Have you applied, or will you apply, for federal or state medical assistance or verified health care exchange eligibility?" value={value.appliedForGovernmentAssistance} onChange={(appliedForGovernmentAssistance) => onChange({ appliedForGovernmentAssistance })} /><TextField label="Reason (optional)" value={value.governmentAssistanceReason ?? ""} onChange={(e) => onChange({ governmentAssistanceReason: e.target.value })} /></div>
    <div className="grid gap-3"><YesNo label="Do you have a lawsuit, settlement, personal injury, or liability claim pending?" value={value.pendingClaim} onChange={(pendingClaim) => onChange({ pendingClaim })} /><TextField label="Reason (optional)" value={value.pendingClaimReason ?? ""} onChange={(e) => onChange({ pendingClaimReason: e.target.value })} /></div>
    <div className="grid gap-3"><YesNo label="Is insurance available through your employer or your spouse's employer?" value={value.employerInsuranceAvailable} onChange={(employerInsuranceAvailable) => onChange({ employerInsuranceAvailable })} /><TextField label="Reason (optional)" value={value.employerInsuranceReason ?? ""} onChange={(e) => onChange({ employerInsuranceReason: e.target.value })} /></div>
    <label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={value.hasSpouse} onChange={(e) => onChange({ hasSpouse: e.target.checked })} />Patient has a spouse or partner</label>
    {value.hasSpouse ? <div className="grid gap-4 md:grid-cols-2"><TextField label="Spouse/partner first name" value={value.spouseFirstName ?? ""} onChange={(e) => onChange({ spouseFirstName: e.target.value })} /><TextField label="Middle name or initial" value={value.spouseMiddleName ?? ""} onChange={(e) => onChange({ spouseMiddleName: e.target.value })} /><TextField label="Last name" value={value.spouseLastName ?? ""} onChange={(e) => onChange({ spouseLastName: e.target.value })} /><TextField label="Birth date" type="date" value={value.spouseBirthDate ?? ""} onChange={(e) => onChange({ spouseBirthDate: e.target.value })} /><label className="grid gap-2 text-sm"><span className="font-medium">Employment status</span><select className="h-11 rounded-md border border-slate-300 bg-white px-3" value={value.spouseEmploymentStatus ?? ""} onChange={(e) => onChange({ spouseEmploymentStatus: e.target.value })}><option value="">Select one</option>{employmentOptions.map((item) => <option key={item}>{item}</option>)}</select></label></div> : null}
    <TextAreaField required label="Dependents" placeholder="Legal names, relationships, and birth dates; enter None if not applicable." value={value.dependentsDetails} onChange={(e) => onChange({ dependentsDetails: e.target.value })} />
    <TextAreaField required label="Other income" placeholder="List other sources and monthly amounts; enter None if not applicable." value={value.otherIncomeDetails} onChange={(e) => onChange({ otherIncomeDetails: e.target.value })} />
    <TextAreaField required label="Medical debt" placeholder="Hospital or doctor, unpaid balance, and monthly payment; enter None if not applicable." value={value.medicalDebtDetails} onChange={(e) => onChange({ medicalDebtDetails: e.target.value })} />
    <label className="flex items-start gap-3 text-sm leading-6"><input className="mt-1" type="checkbox" checked={value.certificationAccepted} onChange={(e) => onChange({ certificationAccepted: e.target.checked })} /><span>I certify this information is true and correct and authorize Mayo Clinic and its affiliates to verify and share it as needed to evaluate financial assistance.</span></label>
    <p className="text-sm text-slate-600">Questions about Mayo Clinic's form: 844-217-9591, Monday–Friday, 8 a.m.–5 p.m.</p>
  </section>;
}
